/* GENERATED by gen_gamedb from gamedb/*.txt - do not edit. */
#include "tb_gamedb.h"

static const int g0_answer_vals[] = {1,2,1,1,2,2,3,1};
static const tb_gamedb_cue g0_cues[] = {
};

/* counts for game 0: 8 answers, 0 cues */
#define G0_NANS 8
#define G0_NCUES 0

static const int g1_answer_vals[] = {2,4,3,2,1,1,2,2,1,2,2};
static const tb_gamedb_cue g1_cues[] = {
};

/* counts for game 1: 11 answers, 0 cues */
#define G1_NANS 11
#define G1_NCUES 0

static const int g2_answer_vals[] = {3,1,1,2,4,3,2,1};
static const tb_gamedb_cue g2_cues[] = {
    { "0D E8 7F EE", 7, 33, 45, 6.40, 8.40, 1 },
};

/* counts for game 2: 8 answers, 1 cues */
#define G2_NANS 8
#define G2_NCUES 1

const tb_gamedb_game tb_gamedb_games[] = {
    { "Mario to Yoshi no Bouken Land", "", g0_answer_vals, G0_NANS, g0_cues, G0_NCUES },
    { "Sailor Moon", "AC B2 55 35 FE", g1_answer_vals, G1_NANS, g1_cues, G1_NCUES },
    { "See 'N Say Treasure Hunt", "", g2_answer_vals, G2_NANS, g2_cues, G2_NCUES },
};
const int tb_gamedb_count = 3;
