/*
 * gen_gamedb.c - compile-time generator for the Terebikko game database.
 *
 * Reads the tab-separated event tables in gamedb/*.txt (the decoded timelines for
 * known games, with optional "# name ..." / "# mania_anchor ..." metadata and a
 * "delayed Ns" marker in the Cue column) and emits a C source file defining the
 * game table. The runtime (tb_gamedb.c) uses it to identify a loaded video, apply
 * game-specific delayed cues, and locate the Mania music anchor.
 *
 * Usage: gen_gamedb <out.c> <game1.txt> [game2.txt ...]
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

static double parse_time(const char *s) {
    int m = 0; double sec = 0;
    if (strchr(s, ':')) sscanf(s, "%d:%lf", &m, &sec);
    else sec = atof(s);
    return m * 60.0 + sec;
}

/* read a tab/whitespace field; returns ptr past it, fills out (may be empty) */
static const char *field(const char *p, char *out, size_t n) {
    while (*p == ' ') p++;
    size_t k = 0;
    while (*p && *p != '\t' && *p != '\n' && *p != '\r') { if (k + 1 < n) out[k++] = *p; p++; }
    out[k] = '\0';
    /* trim trailing spaces */
    while (k && out[k-1] == ' ') out[--k] = '\0';
    if (*p == '\t') p++;
    return p;
}

int main(int argc, char **argv) {
    if (argc < 3) { fprintf(stderr, "usage: %s out.c game.txt...\n", argv[0]); return 2; }
    FILE *o = fopen(argv[1], "w");
    if (!o) { perror("out"); return 1; }
    fprintf(o, "/* GENERATED by gen_gamedb from gamedb/*.txt - do not edit. */\n");
    fprintf(o, "#include \"tb_gamedb.h\"\n\n");

    int ngames = 0;
    char names[64][128], anchors[64][32];
    for (int g = 2; g < argc; g++) {
        FILE *f = fopen(argv[g], "r");
        if (!f) { fprintf(stderr, "skip %s\n", argv[g]); continue; }
        int gi = ngames++;
        names[gi][0] = '\0'; anchors[gi][0] = '\0';
        /* default name = filename stem */
        const char *base = strrchr(argv[g], '/'); base = base ? base + 1 : argv[g];
        snprintf(names[gi], sizeof names[gi], "%s", base);
        char *dot = strrchr(names[gi], '.'); if (dot) *dot = '\0';

        char line[512];
        /* The decoded answer-pulse BYTES vary between rips/sample-rates, but the decoded
         * answer VALUES (1-4) are stable, so we fingerprint a game by its answer-value
         * sequence. */
        fprintf(o, "static const int g%d_answer_vals[] = {", gi);
        int nans = 0;
        long pos = ftell(f);
        while (fgets(line, sizeof line, f)) {
            if (line[0] == '#') {
                if (!strncmp(line, "# name ", 7)) { char *nl = strchr(line, '\n'); if (nl) *nl = 0; snprintf(names[gi], sizeof names[gi], "%s", line + 7); }
                else if (!strncmp(line, "# mania_anchor ", 15)) { char *nl = strchr(line, '\n'); if (nl) *nl = 0; snprintf(anchors[gi], sizeof anchors[gi], "%s", line + 15); }
                continue;
            }
            char type[16], st[24], en[24], ans[8], cp[24], cue[32], bytes[32];
            const char *p = line;
            p = field(p, type, sizeof type);  /* col 0 = index # */
            if (!isalpha((unsigned char)type[0])) p = field(p, type, sizeof type);
            p = field(p, st, sizeof st);
            p = field(p, en, sizeof en);
            p = field(p, ans, sizeof ans);
            p = field(p, cp, sizeof cp);
            p = field(p, cue, sizeof cue);
            p = field(p, bytes, sizeof bytes);
            if (strcmp(type, "answer") == 0 && ans[0]) {
                fprintf(o, "%s%s", nans ? "," : "", ans);
                nans++;
            }
        }
        fprintf(o, "};\n");

        /* second pass: delayed cues */
        fseek(f, pos, SEEK_SET);
        fprintf(o, "static const tb_gamedb_cue g%d_cues[] = {\n", gi);
        int ncues = 0;
        char prevtype[16] = "";
        while (fgets(line, sizeof line, f)) {
            if (line[0] == '#') continue;
            char type[16], st[24], en[24], ans[8], cp[24], cue[40], bytes[32];
            const char *p = line;
            p = field(p, type, sizeof type);
            if (!isalpha((unsigned char)type[0])) p = field(p, type, sizeof type);
            p = field(p, st, sizeof st);
            p = field(p, en, sizeof en);
            p = field(p, ans, sizeof ans);
            p = field(p, cp, sizeof cp);
            p = field(p, cue, sizeof cue);
            p = field(p, bytes, sizeof bytes);
            if (strcmp(type, "answer") == 0 && strncmp(cue, "delayed", 7) == 0) {
                double gap = atof(cue + 7);          /* "delayed 7.4s" -> 7.4 */
                double t = parse_time(st);
                int minute = (int)(t / 60);
                double sec = t - minute * 60;
                fprintf(o, "    { \"%s\", %d, %d, %d, %.2f, %.2f, %d },\n",
                        bytes, minute, (int)(sec - 5), (int)(sec + 7),
                        gap - 1.0, gap + 1.0, strcmp(prevtype, "sound") == 0 ? 1 : 0);
                ncues++;
            }
            strncpy(prevtype, type, sizeof prevtype - 1);
        }
        fprintf(o, "};\n\n");
        fclose(f);

        fprintf(o, "/* counts for game %d: %d answers, %d cues */\n", gi, nans, ncues);
        (void)nans;
        /* stash counts via macros referenced below */
        fprintf(o, "#define G%d_NANS %d\n#define G%d_NCUES %d\n\n", gi, nans, gi, ncues);
    }

    fprintf(o, "const tb_gamedb_game tb_gamedb_games[] = {\n");
    for (int gi = 0; gi < ngames; gi++) {
        fprintf(o, "    { \"%s\", \"%s\", g%d_answer_vals, G%d_NANS, g%d_cues, G%d_NCUES },\n",
                names[gi], anchors[gi], gi, gi, gi, gi);
    }
    fprintf(o, "};\n");
    fprintf(o, "const int tb_gamedb_count = %d;\n", ngames);
    fclose(o);
    return 0;
}
